[tool.poetry]
name = "allisonthuanggithubio"
version = "0.1.0"
description = ""
authors = ["allisonthuang <<>>"]

[tool.poetry.dependencies]
python = "^2.7"
poetry = "^1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
